name = "threshold-studio-frontend"
compatibility_date = "2026-09-13"
pages_build_output_dir = "./website"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true

[[r2_buckets]]
binding = "NODE_BUNDLES"
bucket_name = "threshold-node-bundles"
